### ISSUE TITLE
add_manual does not remove expected number of results

### ISSUE THREAD

**Issue by LukasWallrich** [camaradesuk/ASySD#40]
Based on my understanding, add_manual should remove as many rows as the number of pairs passed? However, for me it removes many fewer. If helpful, I could try to zoom in on the problem - but maybe my assumption is wrong?

``` r
nrow(deduped$unique)
#> [1] 3298
nrow(deduped$manual_dedup)
#> [1] 112
deduped_final <- ASySD::dedup_citations_add_manual(deduped$unique, additional_pairs = deduped$manual_dedup)
nrow(deduped_final)
#> [1] 3241
```

[ASySD output.RDS.zip](https://github.com/camaradesuk/ASySD/files/14522919/ASySD.output.RDS.zip)

**Comment by kaitlynhair** [comment]
Hey @LukasWallrich - wouldn't expect it to map on as exactly the same number due to some duplicates in the manual reconcilaition rows. See example: 

manual dedup pairs:
111 - 222
125 - 347
222 - 896
347 - 896
347 - 222
347 - 111

rows removed with ids: 
896
347
222
125

rows retained:
111

I couldn't replicate this - I get  3190 in dedup_final which seems more accurate. I thought maybe your latest bug fix had sorted it, but I couldn't replicate in 0.3.4 either. Can you test this is now working for you?

**Comment by LukasWallrich** [comment]
Thanks for the explanation (and I now also get 3190, which is better). 

I wonder whether this happens often enough to update the list during the manual screening (in #41)? When you go down the list above, there is no point in judging `347 - 896` if the previous ones have been identified as duplicates ... but that is probably quite fiddly to implement, and maybe not important enough (if my counting is right, it would have saved 4 comparisons in this large dataset). In any case, closing this issue.
